// Excel renderers for the Reports page. Each workbook is built from the SAME
// payload the page renders — an export that re-derives totals eventually
// disagrees with the screen it came from.

const ExcelJS = require('exceljs');

const MONEY_FMT = '"$"#,##0.00;[Red]("$"#,##0.00)';
const HEADER_FILL = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF4F46E5' } };

function styleHeader(row) {
  row.font = { bold: true, color: { argb: 'FFFFFFFF' } };
  row.eachCell((c) => { c.fill = HEADER_FILL; });
}
function moneyCells(row, fromCol) {
  row.eachCell((c, i) => { if (i >= fromCol) c.numFmt = MONEY_FMT; });
}
function noteRow(ws, text) {
  const r = ws.addRow([text]);
  r.font = { italic: true, color: { argb: 'FF6B7280' }, size: 9 };
  return r;
}

async function pnlWorkbook(pnl, { from, to, artist }) {
  const wb = new ExcelJS.Workbook();
  const ws = wb.addWorksheet('P&L', { pageSetup: { orientation: 'landscape' }, views: [{ state: 'frozen', xSplit: 1, ySplit: 3 }] });
  const months = pnl.months;

  const title = ws.addRow([`Profit & Loss — ${from} to ${to}${artist ? ` · ${artist}` : ''}`]);
  title.font = { bold: true, size: 13 };
  noteRow(ws, `Cash basis (ledger-mastered), bank coverage disclosed per month${pnl.reassigned.count ? `, with ${pnl.reassigned.count} recorded period adjustment${pnl.reassigned.count === 1 ? '' : 's'}` : ''}. Generated by Cadence.`);
  const head = ws.addRow(['', ...months, 'Total']);
  styleHeader(head);
  ws.getColumn(1).width = 30;
  for (let i = 2; i <= months.length + 2; i++) ws.getColumn(i).width = 14;

  const lineRow = (name, line, negate = false) => {
    const sign = negate ? -1 : 1;
    const r = ws.addRow([name, ...months.map((m) => sign * (line.series[m] || 0)), sign * line.total]);
    moneyCells(r, 2);
    return r;
  };
  const totalRow = (name, totals) => {
    const r = ws.addRow([name, ...months.map((m) => totals.series[m] || 0), totals.total]);
    r.font = { bold: true };
    moneyCells(r, 2);
    return r;
  };
  const seriesFromNet = () => {
    const s = {};
    for (const m of months) s[m] = (pnl.income_totals.series[m] || 0) - (pnl.expense_totals.series[m] || 0);
    return { series: s, total: pnl.net };
  };

  ws.addRow(['Income']).font = { bold: true };
  for (const [name, line] of Object.entries(pnl.income)) lineRow(name, line);
  totalRow('Total Income', pnl.income_totals);
  ws.addRow([]);
  ws.addRow(['Expenses']).font = { bold: true };
  for (const [name, line] of Object.entries(pnl.expenses)) lineRow(name, line);
  totalRow('Total Expenses', pnl.expense_totals);
  ws.addRow([]);
  totalRow('Net Income (operating)', seriesFromNet());

  // Below-the-line and Non-recurring are TWO sections with two nets. Net
  // Change in Cash is the three-section sum — a workbook that folds them
  // together labels one of them as the other.
  const nr = pnl.non_recurring || { income: {}, expenses: {}, income_totals: { series: {}, total: 0 }, expense_totals: { series: {}, total: 0 }, net: 0 };
  const sectionBlock = (title, block, netLabel) => {
    if (!Object.keys(block.income).length && !Object.keys(block.expenses).length) return false;
    ws.addRow([]);
    ws.addRow([title]).font = { bold: true };
    for (const [name, line] of Object.entries(block.income)) lineRow(name, line);
    for (const [name, line] of Object.entries(block.expenses)) lineRow(name, line, true);
    const net = { series: {}, total: block.net };
    for (const m of months) net.series[m] = (block.income_totals.series[m] || 0) - (block.expense_totals.series[m] || 0);
    totalRow(netLabel, net);
    return true;
  };
  const hasBelow = sectionBlock('Below the line — advances & pass-through', pnl.below, 'Below-line net');
  const hasNr = sectionBlock('Non-recurring', nr, 'Non-recurring net');
  if (hasBelow || hasNr) {
    ws.addRow([]);
    const cash = { series: {}, total: pnl.net + pnl.below.net + nr.net };
    for (const m of months) {
      cash.series[m] = (pnl.income_totals.series[m] || 0) - (pnl.expense_totals.series[m] || 0)
        + (pnl.below.income_totals.series[m] || 0) - (pnl.below.expense_totals.series[m] || 0)
        + (nr.income_totals.series[m] || 0) - (nr.expense_totals.series[m] || 0);
    }
    totalRow('Net Change in Cash', cash);
  }

  if (pnl.dismissed.count || pnl.dismissed.category_count) {
    ws.addRow([]);
    noteRow(ws, `NOTE — ${pnl.dismissed.count} item(s) and ${pnl.dismissed.category_count} whole line(s) are dismissed and not counted above ($${pnl.dismissed.total.toFixed(2)}).`);
  }
  if (pnl.reassigned.moved_out.count) {
    noteRow(ws, `NOTE — ${pnl.reassigned.moved_out.count} row(s) ($${pnl.reassigned.moved_out.total.toFixed(2)}) were moved OUTSIDE this range by period adjustments and appear in no column above.`);
  }
  for (const c of pnl.contra) {
    noteRow(ws, `NOTE — ${c.target} is shown net of $${c.total.toFixed(2)} recovered (${c.income_type}).`);
  }
  return wb.xlsx.writeBuffer();
}

async function spendByArtistWorkbook(data, { from, to, topN }) {
  const wb = new ExcelJS.Workbook();
  const ws = wb.addWorksheet('Spend by Artist', { views: [{ state: 'frozen', xSplit: 1, ySplit: 3 }] });
  const rows = topN ? data.rows.slice(0, topN) : data.rows;
  // Same column order the screen uses — artist-attributable spend first,
  // overhead-only columns last — so the workbook and the page read alike.
  const shownCats = new Set(rows.flatMap((r) => Object.keys(r.by_category)));
  const cats = (data.category_order?.length
    ? data.category_order.map((c) => c.category)
    : [...shownCats].sort((a, b) => rows.reduce((s, r) => s + (r.by_category[b] || 0), 0) - rows.reduce((s, r) => s + (r.by_category[a] || 0), 0))
  ).filter((c) => shownCats.has(c));

  ws.addRow([`Spend by Artist — ${from} to ${to}`]).font = { bold: true, size: 13 };
  noteRow(ws, `Operating spend, ledger-mastered cash basis · advances shown separately${topN ? ` · top ${topN} of ${data.rows.length} artists` : ''}. ties_to_pnl=${data.ties_to_pnl}.`);
  const head = ws.addRow(['Artist', 'Spend', 'Advances', 'Total out', ...cats]);
  styleHeader(head);
  ws.getColumn(1).width = 26;
  for (let i = 2; i <= cats.length + 4; i++) ws.getColumn(i).width = 14;

  for (const r of rows) {
    const row = ws.addRow([r.name, r.total, r.advances, r.total_out, ...cats.map((c) => r.by_category[c] || 0)]);
    moneyCells(row, 2);
  }
  const tot = ws.addRow([
    'TOTAL', data.total, data.advances.total, data.total_out,
    ...cats.map((c) => data.rows.reduce((s, r) => s + (r.by_category[c] || 0), 0)),
  ]);
  tot.font = { bold: true };
  moneyCells(tot, 2);

  ws.addRow([]);
  noteRow(ws, 'What this total excludes:');
  noteRow(ws, `Below-the-line (advances shown in their own column; other pass-through): $${data.excluded.below_line.toFixed(2)}`);
  noteRow(ws, `Excluded by review (dismissed): $${data.excluded.dismissed.total.toFixed(2)} (${data.excluded.dismissed.count})`);
  noteRow(ws, `Moved out of range by period adjustments: $${data.excluded.moved_out.total.toFixed(2)} (${data.excluded.moved_out.count})`);
  noteRow(ws, `Approved but unpaid (not cash yet): $${data.excluded.unpaid.total.toFixed(2)} (${data.excluded.unpaid.count})`);
  if (data.excluded.non_recurring) noteRow(ws, `Non-recurring one-offs held out of operating results: $${data.excluded.non_recurring.toFixed(2)}`);
  if (data.advances.other_total) noteRow(ws, `Below-line spend outside the Advance category (disclosed, not in the Advances column): $${data.advances.other_total.toFixed(2)}`);
  noteRow(ws, `Advances: $${data.advances.attributed_total.toFixed(2)} of $${data.advances.total.toFixed(2)} names an artist${data.advances.advance_only_artists ? `; ${data.advances.advance_only_artists} artist(s) appear only because of an advance` : ''}.`);
  return wb.xlsx.writeBuffer();
}

async function balanceSheetWorkbook(bs) {
  const wb = new ExcelJS.Workbook();
  const ws = wb.addWorksheet('Balance Sheet');
  ws.getColumn(1).width = 36;
  ws.getColumn(2).width = 16;
  ws.addRow([`Balance Sheet — as of ${bs.as_of}`]).font = { bold: true, size: 13 };
  noteRow(ws, 'Cash from the latest captured statement balances. Generated by Cadence.');
  ws.addRow([]);
  ws.addRow(['Assets']).font = { bold: true };
  for (const c of bs.cash.accounts) {
    const r = ws.addRow([`Cash — ${c.account} (as of ${c.as_of})${c.excluded ? ' [excluded]' : ''}`, c.excluded ? 0 : c.balance]);
    r.getCell(2).numFmt = MONEY_FMT;
  }
  const ar = ws.addRow([`Accounts receivable (${bs.accounts_receivable.count})`, bs.accounts_receivable.total]);
  ar.getCell(2).numFmt = MONEY_FMT;
  const agingRows = (label, aging) => {
    if (!aging) return;
    const parts = [['current', 'current'], ['31-60 days', 'd31_60'], ['61-90 days', 'd61_90'], ['90+ days', 'd90_plus']];
    noteRow(ws, `${label} aging — ${parts.map(([l, k]) => `${l} $${(aging[k] || 0).toFixed(2)}`).join(' · ')}`);
  };
  agingRows('A/R', bs.accounts_receivable.aging);
  const ta = ws.addRow(['Total assets', bs.total_assets]);
  ta.font = { bold: true }; ta.getCell(2).numFmt = MONEY_FMT;
  ws.addRow([]);
  ws.addRow(['Liabilities']).font = { bold: true };
  const ap = ws.addRow([`Accounts payable (${bs.accounts_payable.count})`, bs.accounts_payable.total]);
  ap.getCell(2).numFmt = MONEY_FMT;
  agingRows('A/P', bs.accounts_payable.aging);
  if (bs.accounts_payable.undated_paid?.count) {
    noteRow(ws, `NOTE — ${bs.accounts_payable.undated_paid.count} paid bill(s) ($${bs.accounts_payable.undated_paid.total.toFixed(2)}) have no payment date and cannot be placed in time; they are excluded from this as-of view.`);
  }
  const tl = ws.addRow(['Total liabilities', bs.total_liabilities]);
  tl.font = { bold: true }; tl.getCell(2).numFmt = MONEY_FMT;
  ws.addRow([]);
  const na = ws.addRow(['Net assets', bs.net_assets]);
  na.font = { bold: true }; na.getCell(2).numFmt = MONEY_FMT;
  // Funded by — drawdowns are financing, not debt; the deficit is derived, so
  // the block balances by construction and is a presentation, not a proof.
  if (bs.funding && !bs.funding.line_excluded) {
    ws.addRow([]);
    ws.addRow(['Funded by']).font = { bold: true };
    const dr = ws.addRow([`Drawdowns received (${bs.advances_outstanding.count})`, bs.funding.drawdowns]);
    dr.getCell(2).numFmt = MONEY_FMT;
    const ad = ws.addRow(['Accumulated deficit', bs.funding.accumulated_deficit]);
    ad.getCell(2).numFmt = MONEY_FMT;
    const ft = ws.addRow(['Total funding', bs.funding.total]);
    ft.font = { bold: true }; ft.getCell(2).numFmt = MONEY_FMT;
    noteRow(ws, bs.funding.note);
    noteRow(ws, bs.advances_outstanding.note);
  }
  ws.addRow([]);
  noteRow(ws, `Memo — $${bs.memo.recoupable.total.toFixed(2)} of recoupable artist spend across ${bs.memo.recoupable.count} entries. ${bs.memo.recoupable.note}`);
  if (bs.excluded.item_count || bs.excluded.lines.length) {
    noteRow(ws, `NOTE — ${bs.excluded.item_count} item(s) ($${bs.excluded.item_total.toFixed(2)}) and ${bs.excluded.lines.length} line(s) are excluded by review.`);
  }
  return wb.xlsx.writeBuffer();
}

module.exports = { pnlWorkbook, spendByArtistWorkbook, balanceSheetWorkbook };
