// Excel renderers for the Reports page. Each workbook is built from the SAME
// payload the page renders — an export that re-derives totals eventually
// disagrees with the screen it came from.

const ExcelJS = require('exceljs');

const MONEY_FMT = '"$"#,##0.00;[Red]("$"#,##0.00)';
const HEADER_FILL = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF4F46E5' } };

function styleHeader(row) {
  row.font = { bold: true, color: { argb: 'FFFFFFFF' } };
  row.eachCell((c) => { c.fill = HEADER_FILL; });
}
function moneyCells(row, fromCol) {
  row.eachCell((c, i) => { if (i >= fromCol) c.numFmt = MONEY_FMT; });
}
function noteRow(ws, text) {
  const r = ws.addRow([text]);
  r.font = { italic: true, color: { argb: 'FF6B7280' }, size: 9 };
  return r;
}

async function pnlWorkbook(pnl, { from, to, artist }) {
  const wb = new ExcelJS.Workbook();
  const ws = wb.addWorksheet('P&L', { pageSetup: { orientation: 'landscape' }, views: [{ state: 'frozen', xSplit: 1, ySplit: 3 }] });
  const months = pnl.months;

  const title = ws.addRow([`Profit & Loss — ${from} to ${to}${artist ? ` · ${artist}` : ''}`]);
  title.font = { bold: true, size: 13 };
  noteRow(ws, `Cash basis, statement-verified${pnl.reassigned.count ? `, with ${pnl.reassigned.count} recorded period adjustment${pnl.reassigned.count === 1 ? '' : 's'}` : ''}. Generated by Cadence.`);
  const head = ws.addRow(['', ...months, 'Total']);
  styleHeader(head);
  ws.getColumn(1).width = 30;
  for (let i = 2; i <= months.length + 2; i++) ws.getColumn(i).width = 14;

  const lineRow = (name, line, negate = false) => {
    const sign = negate ? -1 : 1;
    const r = ws.addRow([name, ...months.map((m) => sign * (line.series[m] || 0)), sign * line.total]);
    moneyCells(r, 2);
    return r;
  };
  const totalRow = (name, totals) => {
    const r = ws.addRow([name, ...months.map((m) => totals.series[m] || 0), totals.total]);
    r.font = { bold: true };
    moneyCells(r, 2);
    return r;
  };
  const seriesFromNet = () => {
    const s = {};
    for (const m of months) s[m] = (pnl.income_totals.series[m] || 0) - (pnl.expense_totals.series[m] || 0);
    return { series: s, total: pnl.net };
  };

  ws.addRow(['Income']).font = { bold: true };
  for (const [name, line] of Object.entries(pnl.income)) lineRow(name, line);
  totalRow('Total Income', pnl.income_totals);
  ws.addRow([]);
  ws.addRow(['Expenses']).font = { bold: true };
  for (const [name, line] of Object.entries(pnl.expenses)) lineRow(name, line);
  totalRow('Total Expenses', pnl.expense_totals);
  ws.addRow([]);
  totalRow('Net Income (operating)', seriesFromNet());

  const hasBelow = Object.keys(pnl.below.income).length || Object.keys(pnl.below.expenses).length;
  if (hasBelow) {
    ws.addRow([]);
    ws.addRow(['Below the line — advances & pass-through']).font = { bold: true };
    for (const [name, line] of Object.entries(pnl.below.income)) lineRow(name, line);
    for (const [name, line] of Object.entries(pnl.below.expenses)) lineRow(name, line, true);
    const belowNet = { series: {}, total: pnl.below.net };
    for (const m of months) belowNet.series[m] = (pnl.below.income_totals.series[m] || 0) - (pnl.below.expense_totals.series[m] || 0);
    totalRow('Below-line net', belowNet);
    ws.addRow([]);
    const cash = { series: {}, total: pnl.net + pnl.below.net };
    for (const m of months) {
      cash.series[m] = (pnl.income_totals.series[m] || 0) - (pnl.expense_totals.series[m] || 0)
        + (pnl.below.income_totals.series[m] || 0) - (pnl.below.expense_totals.series[m] || 0);
    }
    totalRow('Net Change in Cash', cash);
  }

  if (pnl.dismissed.count || pnl.dismissed.category_count) {
    ws.addRow([]);
    noteRow(ws, `NOTE — ${pnl.dismissed.count} item(s) and ${pnl.dismissed.category_count} whole line(s) are dismissed and not counted above ($${pnl.dismissed.total.toFixed(2)}).`);
  }
  if (pnl.reassigned.moved_out.count) {
    noteRow(ws, `NOTE — ${pnl.reassigned.moved_out.count} row(s) ($${pnl.reassigned.moved_out.total.toFixed(2)}) were moved OUTSIDE this range by period adjustments and appear in no column above.`);
  }
  for (const c of pnl.contra) {
    noteRow(ws, `NOTE — ${c.target} is shown net of $${c.total.toFixed(2)} recovered (${c.income_type}).`);
  }
  return wb.xlsx.writeBuffer();
}

async function spendByArtistWorkbook(data, { from, to, topN }) {
  const wb = new ExcelJS.Workbook();
  const ws = wb.addWorksheet('Spend by Artist', { views: [{ state: 'frozen', xSplit: 1, ySplit: 3 }] });
  const rows = topN ? data.rows.slice(0, topN) : data.rows;
  const cats = [...new Set(rows.flatMap((r) => Object.keys(r.by_category)))].sort(
    (a, b) => rows.reduce((s, r) => s + (r.by_category[b] || 0), 0) - rows.reduce((s, r) => s + (r.by_category[a] || 0), 0)
  );

  ws.addRow([`Spend by Artist — ${from} to ${to}`]).font = { bold: true, size: 13 };
  noteRow(ws, `Operating spend, statement-verified cash basis · advances shown separately${topN ? ` · top ${topN} of ${data.rows.length} artists` : ''}. ties_to_pnl=${data.ties_to_pnl}.`);
  const head = ws.addRow(['Artist', 'Spend', 'Advances', 'Total out', ...cats]);
  styleHeader(head);
  ws.getColumn(1).width = 26;
  for (let i = 2; i <= cats.length + 4; i++) ws.getColumn(i).width = 14;

  for (const r of rows) {
    const row = ws.addRow([r.name, r.total, r.advances, r.total_out, ...cats.map((c) => r.by_category[c] || 0)]);
    moneyCells(row, 2);
  }
  const tot = ws.addRow([
    'TOTAL', data.total, data.advances.total, data.total_out,
    ...cats.map((c) => data.rows.reduce((s, r) => s + (r.by_category[c] || 0), 0)),
  ]);
  tot.font = { bold: true };
  moneyCells(tot, 2);

  ws.addRow([]);
  noteRow(ws, 'What this total excludes:');
  noteRow(ws, `Below-the-line (advances shown in their own column; other pass-through): $${data.excluded.below_line.toFixed(2)}`);
  noteRow(ws, `Excluded by review (dismissed): $${data.excluded.dismissed.total.toFixed(2)} (${data.excluded.dismissed.count})`);
  noteRow(ws, `Moved out of range by period adjustments: $${data.excluded.moved_out.total.toFixed(2)} (${data.excluded.moved_out.count})`);
  noteRow(ws, `Approved but unpaid (not cash yet): $${data.excluded.unpaid.total.toFixed(2)} (${data.excluded.unpaid.count})`);
  if (data.advances.other_total) noteRow(ws, `Below-line spend outside the Advance category (disclosed, not in the Advances column): $${data.advances.other_total.toFixed(2)}`);
  return wb.xlsx.writeBuffer();
}

async function balanceSheetWorkbook(bs) {
  const wb = new ExcelJS.Workbook();
  const ws = wb.addWorksheet('Balance Sheet');
  ws.getColumn(1).width = 36;
  ws.getColumn(2).width = 16;
  ws.addRow([`Balance Sheet — as of ${bs.as_of}`]).font = { bold: true, size: 13 };
  noteRow(ws, 'Cash from the latest captured statement balances. Generated by Cadence.');
  ws.addRow([]);
  ws.addRow(['Assets']).font = { bold: true };
  for (const c of bs.cash.accounts) {
    const r = ws.addRow([`Cash — ${c.account} (as of ${c.as_of})${c.excluded ? ' [excluded]' : ''}`, c.excluded ? 0 : c.balance]);
    r.getCell(2).numFmt = MONEY_FMT;
  }
  const ar = ws.addRow([`Accounts receivable (${bs.accounts_receivable.count})`, bs.accounts_receivable.total]);
  ar.getCell(2).numFmt = MONEY_FMT;
  const ta = ws.addRow(['Total assets', bs.total_assets]);
  ta.font = { bold: true }; ta.getCell(2).numFmt = MONEY_FMT;
  ws.addRow([]);
  ws.addRow(['Liabilities']).font = { bold: true };
  const ap = ws.addRow([`Accounts payable (${bs.accounts_payable.count})`, bs.accounts_payable.total]);
  ap.getCell(2).numFmt = MONEY_FMT;
  if (bs.advances_outstanding.count > 0 || bs.advances_outstanding.total) {
    const adv = ws.addRow([`Advances outstanding (${bs.advances_outstanding.count})`, bs.advances_outstanding.total]);
    adv.getCell(2).numFmt = MONEY_FMT;
    noteRow(ws, bs.advances_outstanding.note);
  }
  const tl = ws.addRow(['Total liabilities', bs.total_liabilities]);
  tl.font = { bold: true }; tl.getCell(2).numFmt = MONEY_FMT;
  ws.addRow([]);
  const na = ws.addRow(['Net assets', bs.net_assets]);
  na.font = { bold: true }; na.getCell(2).numFmt = MONEY_FMT;
  ws.addRow([]);
  noteRow(ws, `Memo — $${bs.memo.recoupable.total.toFixed(2)} of recoupable artist spend across ${bs.memo.recoupable.count} entries. ${bs.memo.recoupable.note}`);
  if (bs.excluded.item_count || bs.excluded.lines.length) {
    noteRow(ws, `NOTE — ${bs.excluded.item_count} item(s) ($${bs.excluded.item_total.toFixed(2)}) and ${bs.excluded.lines.length} line(s) are excluded by review.`);
  }
  return wb.xlsx.writeBuffer();
}

module.exports = { pnlWorkbook, spendByArtistWorkbook, balanceSheetWorkbook };
